name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # all branches and tags

    - name: "Use NodeJS"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci
        npx lerna bootstrap

    - name: Run tests
      run: npx lerna exec npm run test
