name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use NodeJS"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: "Version"
      run: 
        npx lerna version --conventional-commits --yes